# Generated by Django 4.2.3 on 2023-08-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_last_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstoremodel',
            old_name='catagory',
            new_name='category',
        ),
    ]
